# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = "$directory$character"
right_format = "$all"

[directory]
truncation_length = 1

[character]
format = "[Зѓег ](bold green) "
