# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = "$directory $all $character"
add_newline = true
[directory]
truncation_length = 1

[character]
format = "[ô‚¨ª ](bold green) "
