# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = "$directory"
add_newline = true

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '
